### ISSUE TITLE
[BUG] Crash on opening latest plugin version

### ISSUE THREAD

**Issue by K-Meech** [brainglobe/brainglobe-registration#32]
**Describe the bug**
On opening Napari, and selecting `Plugins > BrainGlobe Registration`, it crashes with `Process finished with exit code -1073741819 (0xC0000005)`

**To Reproduce**
I have a local development environment setup like so:
```
conda create -n brainglobe-dev -c conda-forge python=3.10 napari
conda activate brainglobe-dev
pip install -e .[dev]
pip install lxml_html_clean
```
Then I open Napari, and select `Plugins > BrainGlobe Registration`.

**Computer used (please complete the following information):**

- OS: Windows
- Version: Windows 11, version 23H2

**Comment by IgorTatarnikov** [comment]
Odd! I just replicated this on a fresh environment in Ubuntu as well.

It seems the culprit is itk-5.4rc3? Downgrading to itk-5.4rc2 seemed to work for me. Does that also fix it on Windows?

**Comment by K-Meech** [comment]
I just checked - and this works for windows too. Thanks @IgorTatarnikov !
